# This beginner-level config uses the CPU (gpuID: -1) 
# to compress RGB video
# using ffmpeg's X264 codec

# Recording parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 30

# Camera parameters
numCams: 1
cameraMake: "basler"
cameraSettings: "./configs/rgb24.pfs"
frameWidth: 1152
frameHeight: 1024

# Compression parameters
gpuID: -1
pixelFormatInput: "rgb24"
pixelFormatOutput: "rgb0"
quality: 17
ffmpegLogLevel: "warning"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
displayFrameRate: 10

# Trigger parameters
cameraTrigger: "software"
