# This beginner-level example config uses 
# Intel's integrated GPU ("Quick Sync Video")
# to save the video to disk**
# **Video stream is lossless (not compressed)
# Intel dedicated GPUs (DG1, DG2) will be supported in a future release

# Recording parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 30

# Camera parameters
numCams: 1
cameraMake: "basler"
cameraSettings: "./configs/rgb24.pfs"
frameWidth: 1152
frameHeight: 1024

# Compression parameters
gpuID: 0
gpuMake: "intel"                # iGPU "Quick Sync"
pixelFormatInput: "rgb24"       # "rgb24", "gray"
pixelFormatOutput: "rgb0" 
codec: "h264"                   # "h264", "h265"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
displayFrameRate: 10