# This moderate-level config uses the GPU 
# to compress 3 RGB streams in parallel

# Video parameters
videoFolder: "G:/videos/ncam/test3_2688_1536_50fps_2GPU_128Mgpubuf_300Mbps_dual/"
videoFilename: "0.mp4"
frameRate: 60
recTimeInSec: 12

# Camera parameters
numCams: 1
cameraSelection: [1] #,2,3] #,5,6]
cameraNames: ["Camera4"] #, "Camera5","Camera6"] #["Camera1","Camera2","Camera3", "Camera4", "Camera5","Camera6"]
cameraMake: "flir"
cameraSettings: "./configs/rgb24.pfs"
pixelFormatInput: "bayer_bggr8" #"rgb24"
pixelFormatOutput: "rgb0"  #"bgr0" #"yuv420p" #"bgr8" #"rgb0" #"rgb444le" #"nv21" #
frameWidth:  1152 #[1152,3072,2944] #3072 #3072 #2944 #2944 #2816 #2816 #2816 #2688 #1152 #3168 #2304 #1280
frameHeight: 1024 #1920 #1792 #1792 #1664 #1664 #1536 #1664 #1536 #1024 #2176 #2048 #1024
offsetX: 128 #400
offsetY: 368 #100


# Flir settings
bufferSize: 1500
cameraExposureTimeInUs: 3582 #11638
cameraGain: 10.4
disableGamma: False #True
cameraDebug: False #True
ADCBits: "8"
printWriteQueue: False #True #500
packetDelay: 1000
MaxIncompleteImages: 200 #1000

# Compression parameters
gpuID: 0 #[0,0,0] #,0,0] #[0,0,0,1,1,1]  #[1,1,1,1,1,1] #[0,0,0,0,0,0] #[0,0,0,1,1,1]                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h264"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55
rateControl: "1"                      #"0"
maxBitRate: "950000000" #"600000000"
avgBitRate: "300000000" #"300000000"
gpuBuffer: "128M" #"256M"
ffmpegLogLevel: "info"               # "quiet", "warning", "info"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
chunkLengthInSec: 5 #30
displayFrameRate: -5 #10

# Trigger Parameters
triggerController: 'arduino' #"None"
startArduino: True
serialPort: "COM3"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
digitalPins: [9]
cameraTrigger: "Line2"

